### ISSUE TITLE
FileNotFoundException if pepXML has FULL pathname

### ISSUE THREAD

**Issue by vnaum** [Nesvilab/Crystal-C#4]
I have pepXML formatted like this:
```xml
<msms_pipeline_analysis date="2020-10-30T09:06:01" xmlns="http://regis-web.systemsbiology.net/pepXML" summary_xml="/home/ubuntu/philo3-test_01/test_01.pepXML" xsi:schemaLocation="http://sashimi.sourceforge.net/schema_revision/pepXML/pepXML_v118.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<msms_run_summary base_name="/home/ubuntu/philo3-test_01/test_01" raw_data_type="raw" raw_data="raw">
<search_summary base_name="/home/ubuntu/philo3-test_01/test_01" precursor_mass_type="monoisotopic" search_engine="X! Tandem" search_engine_version="MSFragger-3.1.1" fragment_mass_type="monoisotopic" search_id="1">
```

No matter how I specify `raw_file_location` in CrystalC.params (I tried absolute paths, and relative paths) --
it fails like this, like code is blindly concatenating path from pepXML
(w/o stripping path components) to whatever `raw_file_location` is in config file.

```
$ time java -Xmx16G -cp ~/CrystalC-1.3.1.jar crystalc.Run CrystalC.params *.pepXML
Exception in thread "main" umich.ms.fileio.exceptions.FileParsingException: java.io.FileNotFoundException: /MISS/home/ubuntu/philo3-test_01/test_01.mzML (No such file or directory)
        at umich.ms.fileio.filetypes.mzml.MZMLIndexParser.parse(MZMLIndexParser.java:108)
        at umich.ms.fileio.filetypes.mzml.MZMLFile.parseIndex(MZMLFile.java:64)
        at umich.ms.fileio.filetypes.mzml.MZMLFile.fetchIndex(MZMLFile.java:53)
        at umich.ms.fileio.filetypes.mzml.MZMLFile.fetchIndex(MZMLFile.java:29)
        at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parse(AbstractXMLBasedDataSource.java:116)
        at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:807)
        at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:791)
        at crystalc.p_ReadData.LoadRawFile(p_ReadData.java:172)
        at crystalc.Run.ProcessPepXML(Run.java:69)
        at crystalc.Run.main(Run.java:51)
Caused by: java.io.FileNotFoundException: /MISS/home/ubuntu/philo3-test_01/test_01.mzML (No such file or directory)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:127)
        at umich.ms.util.file.AbstractFile.getRandomAccessFile(AbstractFile.java:56)
        at umich.ms.fileio.filetypes.mzml.MZMLIndexParser.parse(MZMLIndexParser.java:79)
        ... 9 more
```

Obvious workaround is to pass "/" as `raw_file_location`, so after appending full path it gets, well, REAL path.

**Comment by huiyinc** [comment]
Hi Vladislav,

Thanks for letting us know.
Yes, we have noticed and resolved this issue in Crystal-C v1.3.2, which is
included in our latest version of FragPipe.
I have updated the tool in our github repository.
Please feel free to give it a try and let us know if you have any questions.
Thanks!

Huiyin

Vladislav Naumov <notifications@github.com> 於 2020年11月2日 下午9:21 寫道：

﻿

I have pepXML formatted like this:

<msms_pipeline_analysis date="2020-10-30T09:06:01"
xmlns="http://regis-web.systemsbiology.net/pepXML"
summary_xml="/home/ubuntu/philo3-test_01/test_01.pepXML"
xsi:schemaLocation="http://sashimi.sourceforge.net/schema_revision/pepXML/pepXML_v118.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<msms_run_summary base_name="/home/ubuntu/philo3-test_01/test_01"
raw_data_type="raw" raw_data="raw">
<search_summary base_name="/home/ubuntu/philo3-test_01/test_01"
precursor_mass_type="monoisotopic" search_engine="X! Tandem"
search_engine_version="MSFragger-3.1.1"
fragment_mass_type="monoisotopic" search_id="1">

No matter how I specify raw_file_location / output_location in
CrystalC.params (I tried absolute paths, and relative paths) --
it fails like this, like code is blindly concatenating path from pepXML
(w/o stripping path components) to whatever raw_file_location /
output_location is in config file.

$ time java -Xmx16G -cp ~/CrystalC-1.3.1.jar crystalc.Run
CrystalC.params *.pepXML
Exception in thread "main"
umich.ms.fileio.exceptions.FileParsingException:
java.io.FileNotFoundException:
/MISS/home/ubuntu/philo3-test_01/test_01.mzML (No such file or
directory)
        at umich.ms.fileio.filetypes.mzml.MZMLIndexParser.parse(MZMLIndexParser.java:108)
        at umich.ms.fileio.filetypes.mzml.MZMLFile.parseIndex(MZMLFile.java:64)
        at umich.ms.fileio.filetypes.mzml.MZMLFile.fetchIndex(MZMLFile.java:53)
        at umich.ms.fileio.filetypes.mzml.MZMLFile.fetchIndex(MZMLFile.java:29)
        at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parse(AbstractXMLBasedDataSource.java:116)
        at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:807)
        at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:791)
        at crystalc.p_ReadData.LoadRawFile(p_ReadData.java:172)
        at crystalc.Run.ProcessPepXML(Run.java:69)
        at crystalc.Run.main(Run.java:51)
Caused by: java.io.FileNotFoundException:
/MISS/home/ubuntu/philo3-test_01/test_01.mzML (No such file or
directory)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:127)
        at umich.ms.util.file.AbstractFile.getRandomAccessFile(AbstractFile.java:56)
        at umich.ms.fileio.filetypes.mzml.MZMLIndexParser.parse(MZMLIndexParser.java:79)
        ... 9 more

Obvious workaround is to pass "/" as raw_file_location / output_location,
so after appending full path it gets, well, REAL path.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Nesvilab/Crystal-C/issues/4>, or unsubscribe
